
language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
#before_script:
 # - npm install -g gulp
cache:
  directories:
    - node_modules

script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "atomjaylee"
  - git config user.email "908105576@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/atomjaylee/atomjaylee.github.io.git
